import {chromium} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import {performance} from 'node:perf_hooks';
import {assertLocalTest,localNetworkOnly} from './local-safety.mjs';
import {login,logout,visibleButton,formWithTitle} from './helpers.mjs';
import {expect} from 'playwright/test';
await assertLocalTest();const data=JSON.parse(await readFile('tests/e2e/fixtures/runtime.json','utf8'));
const resume=process.argv.includes('--resume');
const result=resume?JSON.parse(await readFile('tests/e2e/results/performance/writes.json','utf8')):{environment:'Vite dev + Supabase Local TEST',prefix:`TEST PERF ${Date.now().toString(36)}`,operations:[],products:[],services:[],errors:[]};
const browser=await chromium.launch({headless:true});const context=await browser.newContext({baseURL:'http://localhost:5173',viewport:{width:1440,height:900},timezoneId:'America/Lima',serviceWorkers:'block'});await localNetworkOnly(context);const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));
async function record(name,predicate,action,feedback){await assertLocalTest();const clock=performance.now();const response=page.waitForResponse(predicate);await action();const res=await response;const text=await res.text();const payload=text?JSON.parse(text):null;const responseMs=performance.now()-clock;expect(res.ok()).toBeTruthy();await feedback();const op={name,status:res.status(),path:new URL(res.url()).pathname,responseMs,feedbackMs:performance.now()-clock};result.operations.push(op);console.log(JSON.stringify(op));await writeFile('tests/e2e/results/performance/writes.json',JSON.stringify(result,null,2));return payload;}
try{
  await login(page,'ADMINISTRADOR',data);
  for(let i=0;!resume&&i<3;i++){
    await page.goto('/inventario');await visibleButton(page,'Nuevo producto').click();const form=formWithTitle(page,'Nuevo producto');const name=`${result.prefix} Producto ${i+1}`;
    await form.getByLabel('Nombre',{exact:false}).fill(name);await form.getByLabel('Código de barras',{exact:true}).fill(`TEST-PERF-${Date.now()}-${i}`);await form.getByLabel('Stock inicial',{exact:false}).fill('10');await form.getByLabel('Costo',{exact:false}).fill('0.25');await form.getByLabel('Precio de venta',{exact:false}).fill('1');
    if(i===0){const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2400;c.height=1800;const x=c.getContext('2d');const g=x.createLinearGradient(0,0,2400,1800);g.addColorStop(0,'#cc2266');g.addColorStop(.5,'#99bbee');g.addColorStop(1,'#112244');x.fillStyle=g;x.fillRect(0,0,2400,1800);let seed=12345;for(let y=0;y<1800;y+=6)for(let z=0;z<2400;z+=6){seed=(1664525*seed+1013904223)>>>0;x.fillStyle=`rgba(${seed%256},${seed>>>8&255},${seed>>>16&255},.25)`;x.fillRect(z,y,6,6);}x.fillStyle='white';x.font='180px sans-serif';x.fillText('TEST QA — FICTICIO',140,900);return c.toDataURL('image/png').split(',')[1];});const buffer=Buffer.from(png,'base64');const began=performance.now();await form.locator('input[type=file]').first().setInputFiles({name:'TEST-PERF-2400x1800.png',mimeType:'image/png',buffer});await expect(form.getByText('Cambiar foto',{exact:true})).toBeVisible();const image=await form.locator('img').first().evaluate(async img=>({naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight,...await fetch(img.src).then(r=>r.blob()).then(b=>({bytes:b.size,type:b.type}))}));result.operations.push({name:'Procesar imagen ficticia 2400×1800',sourceBytes:buffer.length,feedbackMs:performance.now()-began,...image});}
    const row=await record(`Crear producto ${i+1}${i===0?' con foto':''}`,r=>r.url().includes('/rest/v1/productos?')&&r.request().method()==='POST',()=>form.getByRole('button',{name:'Guardar',exact:true}).click(),()=>expect(form).toHaveCount(0));const p=Array.isArray(row)?row[0]:row;result.products.push({id:p.id,name,initial:10});await page.reload();await page.getByPlaceholder('Buscar producto...').fill(name);await expect(page.getByRole('row').filter({hasText:name})).toBeVisible();
  }
  for(let i=0;!resume&&i<3;i++){
    await page.goto('/servicios');await visibleButton(page,'Nuevo servicio').click();const form=formWithTitle(page,'Nuevo servicio');const name=`${result.prefix} Servicio ${i+1}`;await form.locator('input[id$="-nombre"]').fill(name);await form.getByLabel('Categoría',{exact:false}).selectOption({label:'Cabello'});await form.getByLabel('Precio',{exact:false}).first().fill('2');await form.getByLabel('Duración (min)',{exact:true}).fill('30');
    const row=await record(`Crear servicio ${i+1}`,r=>r.url().includes('/rest/v1/servicios?')&&r.request().method()==='POST',()=>form.getByRole('button',{name:'Guardar',exact:true}).click(),()=>expect(form).toHaveCount(0));result.services.push({id:(Array.isArray(row)?row[0]:row).id,name});
  }
  await logout(page);await login(page,'CAJERA',data);const own=result.products[0];
  if(resume){result.priorSale=result.sale;result.harnessNote='Primera anulación devolvió cuerpo vacío válido; el script intentó JSON y se detuvo. Se comprobó su persistencia antes de otro ciclo aislado para medir la latencia pendiente.';await page.goto('/historial');await page.getByPlaceholder('Buscar por código o cliente...').fill(result.priorSale.codigo);await page.getByText(result.priorSale.codigo.replace(/^VEN/,'V'),{exact:true}).filter({visible:true}).click();await expect(page.getByText('Anulada',{exact:true}).filter({visible:true})).toBeVisible();await page.goto('/inventario');await page.getByPlaceholder('Buscar producto...').fill(own.name);await expect(page.getByRole('row').filter({hasText:own.name}).getByRole('cell').nth(3)).toHaveText('10');result.priorSaleVerified={state:'ANULADA',stock:10};}
  await page.goto('/ventas');await page.getByRole('searchbox').first().fill(own.name);await page.getByRole('button',{name:new RegExp(own.name)}).click();await visibleButton(page,'+').click();await visibleButton(page,'Yape').click();
  const clock=performance.now();const submitted=page.waitForResponse(r=>r.url().includes('/rpc/confirmar_venta'));await visibleButton(page,'Confirmar venta').click();const paid=await submitted;expect(paid.ok()).toBeTruthy();const b=await paid.json();const sale=Array.isArray(b)?b[0]:b;result.operations.push({name:'Venta POS dos unidades',status:paid.status(),responseMs:performance.now()-clock,feedbackMs:null,limit:'Impresión automática esperada: no se cronometró su diálogo del sistema.'});result.sale=sale;
  // Never confirm again when the expected print opens. Refresh then observe UI stock.
  async function stock(n){const start=performance.now();await page.goto('/inventario');await page.getByPlaceholder('Buscar producto...').fill(own.name);await expect(page.getByRole('row').filter({hasText:own.name}).getByRole('cell').nth(3)).toHaveText(String(n));result.operations.push({name:`Inventario confirma stock ${n}`,feedbackMs:performance.now()-start});await page.reload();await page.getByPlaceholder('Buscar producto...').fill(own.name);await expect(page.getByRole('row').filter({hasText:own.name}).getByRole('cell').nth(3)).toHaveText(String(n));}
  await page.reload();await stock(8);await page.goto('/historial');await page.getByPlaceholder('Buscar por código o cliente...').fill(sale.codigo);await page.getByText(sale.codigo.replace(/^VEN/,'V'),{exact:true}).filter({visible:true}).click();await visibleButton(page,'Anular venta').click();await record('Anular venta',r=>r.url().includes('/rpc/anular_venta'),()=>visibleButton(page,'Sí, anular').click(),()=>expect(page.getByText('Venta anulada. Se devolvió el stock.',{exact:true})).toBeVisible());await stock(10);result.stock={initial:10,sold:2,afterSale:8,final:10,state:'ANULADA'};
  await page.goto('/historial');await page.getByPlaceholder('Buscar por código o cliente...').fill(sale.codigo);await page.getByText(sale.codigo.replace(/^VEN/,'V'),{exact:true}).filter({visible:true}).click();await expect(page.getByText('Anulada',{exact:true}).filter({visible:true})).toBeVisible();
  for(const service of result.services){await page.goto('/servicios');await expect(page.getByRole('row').filter({hasText:service.name})).toBeVisible();}result.servicesPersisted=true;
}finally{await writeFile('tests/e2e/results/performance/writes.json',JSON.stringify(result,null,2));await browser.close();}
