import {test,expect,knownIssue,expectKnownFailure} from './fixtures.mjs';
import {login,visibleButton} from './helpers.mjs';
import {isolatedClient,testImage} from './phase2-helpers.mjs';

for(const a11y of [false,true])test(a11y?'AMPLIACIÓN A11Y PEDIDOS: confirmación modal contiene foco e identifica diálogo':'AMPLIACIÓN DELIVERY: dirección TEST, costo, pedido pendiente y cancelación persistente',async({page,browser,data},info)=>{
  if(a11y)knownIssue(info,'QA-018');
  test.setTimeout(90_000);const own=await isolatedClient(browser,data,'DELIVERY');await login(page,'CLIENTE',own);await page.goto('/mi-perfil/direcciones');await visibleButton(page,'Agregar').click();let form=page.locator('form').filter({has:page.locator('#direccion-etiqueta')});await form.getByLabel('Etiqueta',{exact:false}).fill('TEST Delivery');await form.getByLabel('Dirección',{exact:false}).fill('TEST Calle ficticia 401');await form.getByRole('checkbox',{name:'Usar como predeterminada',exact:true}).check();await form.getByRole('button',{name:'Guardar',exact:true}).click();await expect(form).toHaveCount(0);
  await page.goto('/productos/'+data.saleProductId);await page.getByRole('button',{name:/^Agregar al carrito/}).filter({visible:true}).first().click();const loadedZones=page.waitForResponse(r=>r.url().includes('/rest/v1/zonas_delivery'));await page.goto('/carrito');const zones=await (await loadedZones).json();test.skip(!zones.length,'No hay zonas de delivery configuradas; no se cambia configuración.');await expect(page.getByText('TEST Calle ficticia 401',{exact:true})).toBeVisible();await page.getByLabel('Zona',{exact:true}).selectOption(zones[0].id);
  await visibleButton(page,'Elige el día').click();await page.getByRole('button',{name:String(Number(data.tomorrow.slice(-2))),exact:true}).filter({visible:true}).first().click();await visibleButton(page,'Elige la hora').click();await visibleButton(page,'11:00').click();await expect(page.getByRole('button',{name:/^Confirmar pedido \(/})).toBeDisabled();await page.locator('input[type=file]').setInputFiles(await testImage(page));await expect(page.getByText('Captura adjunta',{exact:true})).toBeVisible();
  const posted=page.waitForResponse(r=>r.url().includes('/rpc/confirmar_pedido_productos'));await page.getByRole('button',{name:/^Confirmar pedido \(/}).click();const submitted=await posted;expect(submitted.ok()).toBeTruthy();const request=submitted.request().postDataJSON();expect(request.p_tipo_entrega).toBe('DELIVERY');expect(request.p_direccion).toBe('TEST Calle ficticia 401');
  const rows=page.waitForResponse(r=>r.url().includes('/rest/v1/pedidos_web?'));await page.goto('/mi-perfil/pedidos');const orders=await (await rows).json();expect(orders).toHaveLength(1);const order=orders[0];expect(order.estado).toBe('PENDIENTE');expect(Number(order.costo_delivery)).toBe(Number(zones[0].costo));expect(Number(order.total)).toBe(Number(order.subtotal)+Number(order.costo_delivery));await expect(page.getByText(data.saleProductName,{exact:false})).toBeVisible();
  await visibleButton(page,'Cancelar pedido').click();const panel=page.getByRole('heading',{name:'¿Cancelar este pedido?',exact:true}).locator('../..');const role=await panel.getAttribute('role');const focus=[];for(let i=0;i<8;i++){await page.keyboard.press('Tab');focus.push(await panel.evaluate(x=>x.contains(document.activeElement)));}await info.attach('delivery-modal-a11y',{body:Buffer.from(JSON.stringify({clientEmail:own.clientEmail,role,ariaModal:await panel.getAttribute('aria-modal'),focusInside:focus})),contentType:'application/json'});await info.attach('delivery-modal',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
  /* QA-030: Escape devuelve el foco a 'Cancelar pedido' y el diálogo se puede reabrir (ciclo de página montada, portal CLIENTE) */await page.keyboard.press('Escape');await expect(panel).toHaveCount(0);expect(await visibleButton(page,'Cancelar pedido').evaluate(x=>x.isConnected&&document.activeElement===x),'Escape debe devolver el foco a Cancelar pedido').toBeTruthy();await visibleButton(page,'Cancelar pedido').click();await expect(panel).toHaveCount(1);
  await visibleButton(page,'Sí, cancelar').click();await expect(page.getByText('Pedido cancelado.',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Cancelado',{exact:true})).toBeVisible();await expect(visibleButton(page,'Cancelar pedido')).toHaveCount(0);await info.attach('delivery-cycle',{body:Buffer.from(JSON.stringify({clientEmail:own.clientEmail,pedidoId:order.id,direccion:order.direccion_entrega,costo:order.costo_delivery,subtotal:order.subtotal,total:order.total,fecha:order.fecha_entrega,final:'CANCELADO',deliveredNotVerified:'QA-009',noRealPayment:true})),contentType:'application/json'});
  if(a11y){expectKnownFailure('QA-018');expect.soft(role).toBe('dialog');expect(focus.every(Boolean)).toBeTruthy();}
});
