import {test,expect,knownIssue,expectKnownFailure} from './fixtures.mjs';
import {login,logout,visibleButton,createService,createAttention,formWithTitle} from './helpers.mjs';
import {isolatedClient,testImage,qaContext} from './phase2-helpers.mjs';

test('AMPLIACIÓN RESERVA: CLIENTE agenda, reprograma, cancela y libera horario',async({page,browser,data},info)=>{
  test.setTimeout(120_000);const own=await isolatedClient(browser,data,'RESERVA');await login(page,'ADMINISTRADOR',data);
  const service={serviceName:`${own.clientName} Servicio`};await createService(page,service);await logout(page);await login(page,'CLIENTE',own);
  await page.goto('/servicios/'+service.serviceId);await visibleButton(page,'Reservar ahora').click();await expect(page).toHaveURL(/\/citas$/);await page.getByRole('link',{name:'Agendar cita',exact:true}).first().click();await expect(page).toHaveURL(/\/citas\/carrito$/);
  await expect(visibleButton(page,'Confirmar reserva')).toBeDisabled();
  const assistants=page.locator('section[aria-labelledby="carrito-asis-titulo"]');await assistants.getByRole('button').filter({hasText:/test/i}).first().click();
  const dates=page.locator('section[aria-labelledby="carrito-fecha-titulo"]');const dayButtons=dates.getByRole('button').filter({hasText:/^(lun|mar|mié|jue|vie|sáb|dom) \d+$/i});
  const usable=await dayButtons.evaluateAll(xs=>xs.map((x,i)=>({i,disabled:x.disabled,text:x.textContent})).filter(x=>!x.disabled));expect(usable.length).toBeGreaterThan(2);
  const availability=page.waitForResponse(r=>r.url().includes('/rpc/horarios_disponibles_cita'));await dayButtons.nth(usable[2].i).click();const available=await (await availability).json();expect(available.length).toBeGreaterThan(1);
  const hours=dates.getByRole('button').filter({hasText:/^\d{1,2}:\d{2}/});await hours.first().click();await expect(visibleButton(page,'Confirmar reserva')).toBeDisabled();
  await page.getByPlaceholder('Algo que quieras avisar antes de tu cita (opcional)').fill(own.clientName);
  await page.locator('input[type=file]').setInputFiles(await testImage(page));await expect(page.getByText('Captura adjunta',{exact:true})).toBeVisible();
  const booked=page.waitForResponse(r=>r.url().includes('/rpc/agendar_cita_web'));await visibleButton(page,'Confirmar reserva').click();const response=await booked;
  const body=await response.json();await info.attach('reserve-result',{body:Buffer.from(JSON.stringify({status:response.status(),body,client:own.clientName,service:service.serviceName,slot:available[0].inicio})),contentType:'application/json'});expect(response.ok()).toBeTruthy();
  await expect(page).toHaveURL(/\/citas$/);await page.reload();const next=page.locator('section[aria-labelledby="citas-proxima-titulo"]');await expect(next.getByText(service.serviceName,{exact:true})).toBeVisible();await expect(next.getByText('Pendiente',{exact:true})).toBeVisible();
  await next.getByRole('button',{name:'Reprogramar',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Reprogramar cita',exact:true});await expect(dialog.getByRole('checkbox',{name:new RegExp(service.serviceName)})).toBeChecked();
  await dialog.getByLabel('Nota (opcional)',{exact:true}).fill(own.clientName+' REPROGRAMADA');await dialog.getByRole('button').filter({hasText:/^\d{1,2}:\d{2}/}).nth(1).click();
  const reprogrammed=page.waitForResponse(r=>r.url().includes('/rpc/reprogramar_mi_cita_web'));await dialog.getByRole('button',{name:'Confirmar',exact:true}).click();const changed=await reprogrammed;expect(changed.ok()).toBeTruthy();const changedSlot=changed.request().postDataJSON().p_nueva_fecha_hora;expect(new Date(changedSlot).getTime()).not.toBe(new Date(available[0].inicio).getTime());await expect(dialog).toHaveCount(0);
  await page.waitForLoadState('networkidle');const persisted=page.waitForResponse(r=>r.url().includes('/rest/v1/citas?')&&r.request().method()==='GET'&&r.url().includes('asistente_id')).then(r=>r.json());await page.reload();const savedCitas=await persisted;const stored=savedCitas.find(x=>x.id===body);expect(new Date(stored.fecha_hora).getTime()).toBe(new Date(changedSlot).getTime());
  await next.getByRole('button',{name:'Reprogramar',exact:true}).click();await expect(dialog.getByLabel('Nota (opcional)',{exact:true})).toHaveValue(own.clientName+' REPROGRAMADA');await dialog.getByRole('button',{name:'Volver',exact:true}).click();
  await next.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByRole('dialog',{name:'¿Cancelar esta cita?',exact:true}).getByRole('button',{name:'Volver',exact:true}).click();await expect(next.getByText(service.serviceName,{exact:true})).toBeVisible();
  await next.getByRole('button',{name:'Cancelar',exact:true}).click();const cancelled=page.waitForResponse(r=>r.url().includes('/rpc/cancelar_mi_cita_web'));await page.getByRole('dialog',{name:'¿Cancelar esta cita?',exact:true}).getByRole('button',{name:'Sí, cancelar',exact:true}).click();expect((await cancelled).ok()).toBeTruthy();await page.reload();await expect(page.getByText('Cancelada',{exact:true}).filter({visible:true}).first()).toBeVisible();
  await page.goto('/servicios/'+service.serviceId);await visibleButton(page,'Reservar ahora').click();await page.getByRole('link',{name:'Agendar cita',exact:true}).first().click();await assistants.getByRole('button').filter({hasText:/test/i}).first().click();const after=page.waitForResponse(r=>r.url().includes('/rpc/horarios_disponibles_cita'));await dayButtons.nth(usable[2].i).click();const free=await (await after).json();expect(free.some(x=>new Date(x.inicio).getTime()===new Date(changedSlot).getTime())).toBeTruthy();expect(free.some(x=>x.inicio===available[0].inicio)).toBeTruthy();
  await info.attach('reserve-cycle',{body:Buffer.from(JSON.stringify({clientEmail:own.clientEmail,serviceId:service.serviceId,citaId:body,initialSlot:available[0].inicio,savedSlot:stored.fecha_hora,cancelled:true,slotAvailableAgain:true,noRealPayment:true})),contentType:'application/json'});
});

test('AMPLIACIÓN COMISIÓN: ASISTENTE sin porcentaje guarda pendiente y no puede confirmar',async({page,data},info)=>{
  await login(page,'ADMINISTRADOR',data);const service={serviceName:`${data.prefix} SIN PORCENTAJE ${Date.now().toString(36)}`};await createService(page,service);await logout(page);await login(page,'ASISTENTE',data);
  await page.goto('/mi-panel');const summaries=[];page.on('response',async r=>{if(r.url().includes('/rpc/resumen_mi_panel')&&r.ok())summaries.push(await r.json());});
  await visibleButton(page,'Registrar atención').click();const form=formWithTitle(page,'Registrar atención');await form.getByPlaceholder('Buscar cliente...').fill(data.clientName);await form.getByRole('button',{name:data.clientName,exact:true}).click();await form.getByPlaceholder('Buscar servicio...').fill(service.serviceName);await form.getByRole('button',{name:new RegExp('^'+service.serviceName)}).first().click();
  await expect(form.getByRole('button',{name:'Guardar',exact:true})).toBeDisabled();const pending=form.getByRole('button',{name:'Anotar como pendiente (sin comisión por ahora)',exact:true});await expect(pending).toBeVisible();
  const insert=page.waitForResponse(r=>r.url().includes('/rest/v1/registro_servicios')&&r.request().method()==='POST');await pending.click();const saved=await insert;await info.attach('pending-insert',{body:Buffer.from(JSON.stringify({status:saved.status(),body:await saved.text(),service:service.serviceName})),contentType:'application/json'});expect(saved.ok()).toBeTruthy();await expect(form).toHaveCount(0);await page.reload();
  await page.getByPlaceholder('Buscar por servicio o cliente...').fill(service.serviceName);await page.getByRole('button',{name:/0 servicios/}).filter({visible:true}).first().click();await visibleButton(page,'Expandir').first().click();await expect(page.getByText(/Pendiente de comisión —/)).toBeVisible();
  const confirm=page.waitForResponse(r=>r.url().includes('/rest/v1/registro_servicios')&&r.request().method()==='PATCH');await visibleButton(page,'Confirmar').click();const rejected=await confirm;const error=await rejected.json();expect(rejected.ok()).toBeFalsy();expect(error.message).toContain('Sin % asignado');await page.reload();await page.getByPlaceholder('Buscar por servicio o cliente...').fill(service.serviceName);await page.getByRole('button',{name:/0 servicios/}).filter({visible:true}).first().click();await expect(page.getByText('Pendiente',{exact:true}).filter({visible:true})).toBeVisible();
  await info.attach('commission-pending',{body:Buffer.from(JSON.stringify({serviceId:service.serviceId,rejection:error.message,configurationUnchanged:true,summaries})),contentType:'application/json'});
});

for(const redeem of [false,true])test(redeem?'AMPLIACIÓN CANJE: cupón fidelización descuenta 20% y revierte al anular':'AMPLIACIÓN RECOMPENSA: cinco fechas distintas generan un único cupón persistente',async({page,browser,data},info)=>{
  if(redeem)knownIssue(info,'QA-019');
  test.setTimeout(300_000);/* con QA-019 corregido el flujo completo (5 atenciones, canje, anulación) supera los 120 s */const own=await isolatedClient(browser,data,'RECOMPENSA');await login(page,'ADMINISTRADOR',data);
  const dates=[];for(let i=0;i<5;i++){const day=new Date(`${data.today}T12:00:00-05:00`);day.setUTCDate(day.getUTCDate()-i);const date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima'}).format(day);dates.push(date);await createAttention(page,{...own,today:date},'10:15');}
  await logout(page);await login(page,'CLIENTE',own);await page.goto('/fidelizacion');await expect(page.getByText('¡Tarjeta completa!',{exact:true})).toBeVisible();await expect(page.getByText('5 visitas completadas en total.',{exact:true})).toBeVisible();
  const issued=page.waitForResponse(r=>r.url().includes('/rpc/generar_cupon_fidelizacion'));await visibleButton(page,'Generar cupón').dblclick();const response=await issued;const result=await response.json();await info.attach('reward-issued',{body:Buffer.from(JSON.stringify({status:response.status(),result,client:own.clientName,dates})),contentType:'application/json'});expect(response.ok()).toBeTruthy();
  await page.reload();await expect(visibleButton(page,'Generar cupón')).toHaveCount(0);const coupons=page.waitForResponse(r=>r.url().includes('/rpc/mis_cupones'));await page.goto('/ofertas');const rows=await (await coupons).json();const ownCoupons=rows.filter(x=>x.origen==='FIDELIZACION');expect(ownCoupons).toHaveLength(1);expect(ownCoupons[0].estado).toBe('DISPONIBLE');expect(Number(ownCoupons[0].valor)).toBe(20);
  await info.attach('reward-cycle',{body:Buffer.from(JSON.stringify({clientEmail:own.clientEmail,dates,coupons:ownCoupons})),contentType:'application/json'});
  if(!redeem)return;
  await logout(page);await login(page,'CAJERA',data);await page.goto('/ventas');await visibleButton(page,'+ Agregar servicio').click();const attention=page.getByRole('dialog',{name:'Atención a cobrar',exact:true});await attention.getByPlaceholder('Buscar por servicio o cliente...').fill(own.clientName);await attention.getByRole('button',{name:new RegExp('^'+data.serviceName)}).first().click();await attention.getByRole('button',{name:'Cerrar',exact:true}).click();await expect(attention).toHaveCount(0);
  await page.getByRole('button',{name:'Descuento porcentual — cambiar a monto fijo',exact:true}).click();await page.getByRole('button',{name:'Descuento por monto fijo — cambiar a cupón',exact:true}).click();await page.getByLabel('Código de cupón',{exact:true}).fill(ownCoupons[0].codigo);await expect(page.getByText(/^Cupón de /)).toContainText(own.clientName);await visibleButton(page,'Yape').click();
  const charged=page.waitForResponse(r=>r.url().includes('/rpc/confirmar_venta'));await visibleButton(page,'Confirmar venta').click();const paid=await charged;const paidBody=await paid.json();await info.attach('coupon-sale-response',{body:Buffer.from(JSON.stringify({status:paid.status(),request:paid.request().postDataJSON(),response:paidBody,coupon:ownCoupons[0],clientEmail:own.clientEmail})),contentType:'application/json'});
  if(!paid.ok()){expect(paidBody.code).toBe('42702');expect(paidBody.message).toBe('column reference "codigo" is ambiguous');await expect(page.getByText(paidBody.message,{exact:true})).toBeVisible();const check=await qaContext(browser);try{const customer=await check.newPage();await login(customer,'CLIENTE',own);await customer.waitForLoadState('networkidle');const loaded=customer.waitForResponse(r=>r.url().includes('/rpc/mis_cupones')).then(r=>r.json());await customer.goto('/ofertas');const persisted=(await loaded).find(x=>x.codigo===ownCoupons[0].codigo);expect(persisted.estado).toBe('DISPONIBLE');await info.attach('coupon-after-rejection',{body:Buffer.from(JSON.stringify(persisted)),contentType:'application/json'});}finally{await check.close();}}
  expectKnownFailure('QA-019');expect(paid.ok()).toBeTruthy();const sale=Array.isArray(paidBody)?paidBody[0]:paidBody;expect(Number(sale.total)).toBe(1.6);await page.reload();
  const ctx=await qaContext(browser);try{const client=await ctx.newPage();await login(client,'CLIENTE',own);async function readCoupon(){await client.waitForLoadState('networkidle');const loaded=client.waitForResponse(r=>r.url().includes('/rpc/mis_cupones'));await client.goto('/ofertas');return (await (await loaded).json()).find(x=>x.codigo===ownCoupons[0].codigo);}
    expect((await readCoupon()).estado).toBe('CANJEADO');await page.goto('/historial');await page.getByPlaceholder('Buscar por código o cliente...').fill(sale.codigo);await page.getByText(sale.codigo.replace(/^VEN/,'V'),{exact:true}).filter({visible:true}).click();await visibleButton(page,'Anular venta').click();await visibleButton(page,'Sí, anular').click();await expect(page.getByText('Venta anulada. Se devolvió el stock.',{exact:true})).toBeVisible();expect((await readCoupon()).estado).toBe('DISPONIBLE');
    await info.attach('coupon-redemption',{body:Buffer.from(JSON.stringify({couponCode:ownCoupons[0].codigo,sale,subtotal:2,discount:0.4,total:1.6,afterSale:'CANJEADO',afterAnnul:'DISPONIBLE'})),contentType:'application/json'});
  }finally{await ctx.close();}
});

test('AMPLIACIÓN COMISIÓN ADMIN: atención TEST aplica 100%, muestra importe y cancela',async({page,data},info)=>{
  await login(page,'ADMINISTRADOR',data);const service={serviceName:`${data.prefix} COMISION ADMIN ${Date.now().toString(36)}`};await createService(page,service);await createAttention(page,{...data,serviceName:service.serviceName},'12:45');await page.reload();await page.getByPlaceholder('Buscar por servicio o cliente...').fill(service.serviceName);await page.getByRole('button',{name:/1 servicio\b/}).filter({visible:true}).first().click();await visibleButton(page,'Expandir').first().click();await expect(page.getByText('100%',{exact:true})).toBeVisible();await expect(page.getByText(/^Pago asistente:/)).toContainText('2.00');await info.attach('commission-admin',{body:Buffer.from(JSON.stringify({serviceId:service.serviceId,price:2,percentage:100,payment:2})),contentType:'application/json'});await visibleButton(page,'Cancelar').click();await page.getByRole('dialog').getByRole('button',{name:'Sí, cancelar',exact:true}).click();await expect(page.getByText('Atención cancelada.',{exact:true})).toBeVisible();await page.reload();await page.getByPlaceholder('Buscar por servicio o cliente...').fill(service.serviceName);await visibleButton(page,'Mostrar canceladas').click();await page.getByRole('button',{name:/0 servicios/}).filter({visible:true}).first().click();await expect(page.getByText('Cancelada',{exact:true}).filter({visible:true})).toBeVisible();
});
