-- Huella PREVIA de negocio (SOLO LECTURA): por tabla, conteo y md5 de un subconjunto de columnas. Solo salen conteos y hashes,
-- nunca valores. Mismo alcance y limites que RESULTADO-ENSAYO.md seccion 3 (no es identidad completa del contenido).
select 'productos', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,codigo_barras,nombre,precio,costo,stock_actual,activo)::text, '|' order by row(id,codigo_barras,nombre,precio,costo,stock_actual,activo)::text), '')) from public.productos);
select 'servicios', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,nombre,precio,activo)::text, '|' order by row(id,nombre,precio,activo)::text), '')) from public.servicios);
select 'clientes', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,nombre,telefono,cliente_web_id,puntos_bono,fidelizacion_recompensas_reclamadas)::text, '|' order by row(id,nombre,telefono,cliente_web_id,puntos_bono,fidelizacion_recompensas_reclamadas)::text), '')) from public.clientes);
select 'ventas', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,codigo,estado,total,metodo_pago,vendedor_id,cliente_id,descuento_pct,descuento_monto)::text, '|' order by row(id,codigo,estado,total,metodo_pago,vendedor_id,cliente_id,descuento_pct,descuento_monto)::text), '')) from public.ventas);
select 'venta_items', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,venta_id,tipo,nombre,cantidad,precio_unitario,subtotal)::text, '|' order by row(id,venta_id,tipo,nombre,cantidad,precio_unitario,subtotal)::text), '')) from public.venta_items);
select 'citas', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,cliente_id,asistente_id,fecha_hora,estado)::text, '|' order by row(id,cliente_id,asistente_id,fecha_hora,estado)::text), '')) from public.citas);
select 'cita_servicios', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,cita_id,servicio_id,precio)::text, '|' order by row(id,cita_id,servicio_id,precio)::text), '')) from public.cita_servicios);
select 'registro_servicios', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,usuario_id,servicio_id,cliente_id,precio,estado,venta_id)::text, '|' order by row(id,usuario_id,servicio_id,cliente_id,precio,estado,venta_id)::text), '')) from public.registro_servicios);
select 'cupones', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,cliente_id,codigo,origen,valor,estado,tipo_descuento)::text, '|' order by row(id,cliente_id,codigo,origen,valor,estado,tipo_descuento)::text), '')) from public.cupones);
select 'promociones', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,titulo,tipo_descuento,valor,activo)::text, '|' order by row(id,titulo,tipo_descuento,valor,activo)::text), '')) from public.promociones);
select 'pedidos_web', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,cliente_id,estado,total)::text, '|' order by row(id,cliente_id,estado,total)::text), '')) from public.pedidos_web);
select 'config_puntos', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,umbral_vip,umbral_premium,puntos_por_visita,puntos_por_sol_gastado)::text, '|' order by row(id,umbral_vip,umbral_premium,puntos_por_visita,puntos_por_sol_gastado)::text), '')) from public.config_puntos);
select 'config_referidos', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,credito_referido,credito_referidor)::text, '|' order by row(id,credito_referido,credito_referidor)::text), '')) from public.config_referidos);
select 'config_fidelizacion', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,porcentaje_recompensa)::text, '|' order by row(id,porcentaje_recompensa)::text), '')) from public.config_fidelizacion);
select 'usuarios', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,email,rol,activo)::text, '|' order by row(id,email,rol,activo)::text), '')) from public.usuarios);
select 'asistentes', (select count(*)::text || ':' || md5(coalesce(string_agg(row(id,usuario_id,nombres_completos,activo)::text, '|' order by row(id,usuario_id,nombres_completos,activo)::text), '')) from public.asistentes);
select 'porcentajes', (select count(*)::text || ':' || md5(coalesce(string_agg(row(servicio_id,asistente_id,porcentaje)::text, '|' order by row(servicio_id,asistente_id,porcentaje)::text), '')) from public.porcentajes);
