-- Emula los privilegios de PRODUCCIÓN (comprobados solo con lectura el 2026-10-07) en la instancia desechable.
begin;
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public grant truncate, references, trigger, maintain on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public revoke all on functions from public, anon, authenticated, service_role;
alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated, service_role;
revoke all on table public.carrito_servicios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_servicios to anon;
grant INSERT, SELECT, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_servicios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_servicios to service_role;
revoke all on table public.favoritos_productos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_productos to anon;
grant INSERT, SELECT, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_productos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_productos to service_role;
revoke all on table public.favoritos_servicios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_servicios to anon;
grant INSERT, SELECT, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_servicios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.favoritos_servicios to service_role;
revoke all on table public.movimientos_stock from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.movimientos_stock to anon;
grant INSERT, SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.movimientos_stock to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.movimientos_stock to service_role;
revoke all on table public.venta_items from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.venta_items to anon;
grant INSERT, SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.venta_items to authenticated;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.venta_items to service_role;
revoke all on table public.asistentes from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.asistentes to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.asistentes to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.asistentes to service_role;
revoke all on table public.carrito_productos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_productos to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_productos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.carrito_productos to service_role;
revoke all on table public.cita_servicios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cita_servicios to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cita_servicios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cita_servicios to service_role;
revoke all on table public.citas from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.citas to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.citas to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.citas to service_role;
revoke all on table public.clientes from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes to service_role;
revoke all on table public.deudas from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.deudas to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.deudas to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.deudas to service_role;
revoke all on table public.direcciones_cliente from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.direcciones_cliente to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.direcciones_cliente to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.direcciones_cliente to service_role;
revoke all on table public.galeria_web from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.galeria_web to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.galeria_web to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.galeria_web to service_role;
revoke all on table public.gastos_recurrentes from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos_recurrentes to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos_recurrentes to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos_recurrentes to service_role;
revoke all on table public.mobiliario from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario to service_role;
revoke all on table public.mobiliario_compras from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario_compras to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario_compras to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.mobiliario_compras to service_role;
revoke all on table public.porcentajes from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.porcentajes to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.porcentajes to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.porcentajes to service_role;
revoke all on table public.producto_fotos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_fotos to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_fotos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_fotos to service_role;
revoke all on table public.producto_variantes from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_variantes to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_variantes to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.producto_variantes to service_role;
revoke all on table public.promociones from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.promociones to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.promociones to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.promociones to service_role;
revoke all on table public.registro_servicios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.registro_servicios to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.registro_servicios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.registro_servicios to service_role;
revoke all on table public.servicio_fotos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicio_fotos to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicio_fotos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicio_fotos to service_role;
revoke all on table public.servicios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicios to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.servicios to service_role;
revoke all on table public.usuarios from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.usuarios to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.usuarios to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.usuarios to service_role;
revoke all on table public.zonas_delivery from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.zonas_delivery to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.zonas_delivery to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.zonas_delivery to service_role;
revoke all on table public.gastos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos to anon;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos to authenticated;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.gastos to service_role;
revoke all on table public.clientes_web from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes_web to anon;
grant INSERT, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes_web to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.clientes_web to service_role;
revoke all on table public.ventas from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.ventas to anon;
grant INSERT, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.ventas to authenticated;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.ventas to service_role;
revoke all on table public.productos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos to anon;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos to service_role;
revoke all on table public.auditoria from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.auditoria to anon;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.auditoria to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.auditoria to service_role;
revoke all on table public.cupones from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cupones to anon;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cupones to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.cupones to service_role;
revoke all on table public.pedidos_web_items from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web_items to anon;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web_items to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web_items to service_role;
revoke all on table public.productos_vista from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos_vista to anon;
grant SELECT, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos_vista to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.productos_vista to service_role;
revoke all on table public.config_fidelizacion from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_fidelizacion to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_fidelizacion to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_fidelizacion to service_role;
revoke all on table public.config_puntos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_puntos to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_puntos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_puntos to service_role;
revoke all on table public.config_referidos from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_referidos to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_referidos to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.config_referidos to service_role;
revoke all on table public.estado_negocio from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.estado_negocio to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.estado_negocio to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.estado_negocio to service_role;
revoke all on table public.notificaciones from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.notificaciones to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.notificaciones to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.notificaciones to service_role;
revoke all on table public.pedidos_web from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.pedidos_web to service_role;
revoke all on table public.resenas from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas to service_role;
revoke all on table public.resenas_producto from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_producto to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_producto to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_producto to service_role;
revoke all on table public.resenas_servicio from anon, authenticated, service_role;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_servicio to anon;
grant SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_servicio to authenticated;
grant TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on table public.resenas_servicio to service_role;
grant select (id, codigo_barras, nombre, categoria, precio, stock_actual, stock_minimo, proveedor, foto_url, activo, precio_antes, destacado, nuevo, en_inicio, subcategoria, descripcion, contenido, rinde, frecuencia, oferta_hasta, especificaciones, modo_uso, ideal_para, tips, ingredientes, libre_de, combo_con) on table public.productos to authenticated;
do $$ declare r record; begin
 for r in select p.oid::regprocedure f, p.proname n from pg_proc p where p.pronamespace='public'::regnamespace and p.prokind in ('f','p') loop
  execute format('revoke all on function %s from public, anon, authenticated, service_role', r.f);
  if r.n = any(array['actualizar_mi_foto_perfil','agregar_stock','anular_venta','asistentes_para_citas','auditoria_paginada','completar_cita','eliminar_asistente','eliminar_producto','eliminar_servicio','es_admin','es_hoy','historial_stock_producto','resumen_asistentes_periodo','resumen_dashboard','resumen_estadisticas','resumen_historial','resumen_inventario','resumen_mi_panel','rol_actual','usuarios_para_citas']) then execute format('grant execute on function %s to public, authenticated', r.f);
  elsif r.n = any(array['actualizar_mi_foto_cliente','agendar_cita_web','aplicar_codigo_referido','cancelar_mi_cita_web','cancelar_mi_pedido_web','confirmar_pedido_productos','confirmar_venta','datos_contacto','equipo_para_web','existe_cliente_no_vinculado','galeria_para_web','generar_cupon_fidelizacion','guardar_mi_resena','guardar_mi_resena_producto','guardar_mi_resena_servicio','horario_atencion','horarios_disponibles_cita','mi_cliente_id','mi_codigo_referido','mi_estado_referidos','mi_fidelizacion','mi_historial_fidelizacion','mi_perfil_cliente','mi_resena','mi_resena_producto','mi_resena_servicio','mis_cupones','mis_puntos','productos_combo_sugerido','reclamar_cupon_promocion','reprogramar_mi_cita_web','resenas_producto_publicas','resenas_producto_resumen','resenas_publicas','resenas_servicio_publicas','resenas_servicio_resumen','servicios_combo_sugerido','servicios_mas_pedidos','verificar_pago_pedido_web','vincular_o_crear_cliente_web']) then execute format('grant execute on function %s to authenticated', r.f);
  elsif r.n = any(array['calcular_comision_registro_servicio','descripcion_de_fila','generar_codigo_cupon','generar_codigo_referido','marcar_actualizacion_estado_negocio','negocio_abierto','notificar_cambio_pedido_web','notificar_cambio_resena','notificar_cita_cancelada_staff','registrar_auditoria','registrar_auditoria_venta','unicidad_direccion_predeterminada']) then execute format('grant execute on function %s to public', r.f);
  else raise exception 'función sin clasificar: %', r.n; end if;
 end loop; end $$;
alter table public.ventas alter column monto_pos_tarjeta type numeric;
create schema if not exists ensayo_marker;
create table if not exists ensayo_marker.destino(instancia text primary key, creado_en timestamptz default now());
insert into ensayo_marker.destino(instancia) values ('JaiseEnsayo') on conflict do nothing;
commit;